### ISSUE TITLE
[BUG] Build Failure OpenSearchExtensions.kt: (277, 18): Unresolved reference: injectProperty

### ISSUE THREAD

**Issue by peternied** [opensearch-project/index-management#144]
**Describe the bug**

**To Reproduce**
1.  Use [OpenSearch-build workflow](https://github.com/opensearch-project/opensearch-build/) `./bundle-workflow/build.sh manifests/opensearch-1.1.0.yml --component index-management --snapshot`

Test output
```
> Task :compileKotlin
e: /tmp/tmpm8u86961/index-management/src/main/kotlin/org/opensearch/indexmanagement/opensearchapi/OpenSearchExtensions.kt: (277, 18): Unresolved reference: injectProperty

> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 4s
2 actionable tasks: 2 executed
2021-09-10 19:43:32 ERROR    Error building index-management, retry with: /var/jenkins/workspace/bundle-build/bundle-workflow/build.sh manifests/opensearch-1.1.0.yml --component index-management --snapshot
Traceback (most recent call last):
  File "/var/jenkins/workspace/bundle-build/bundle-workflow/src/build.py", line 63, in <module>
    builder.build(manifest.build.version, arch, args.snapshot)
  File "/var/jenkins/workspace/bundle-build/bundle-workflow/src/build_workflow/builder.py", line 37, in build
    self.git_repo.execute(build_command)
  File "/var/jenkins/workspace/bundle-build/bundle-workflow/src/git/git_repository.py", line 67, in execute
    subprocess.check_call(command, cwd=cwd, shell=True)
  File "/usr/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/var/jenkins/workspace/bundle-build/bundle-workflow/scripts/default/build.sh -v 1.1.0 -a x64 -s true -o artifacts' returned non-zero exit status 1.
```

**Comment by bowenlan-amzn** [comment]
Missing one commit in common-utils 1.1 branch, PR for backport that: https://github.com/opensearch-project/common-utils/pull/70

**Comment by peternied** [comment]
Confirmed resolved in build 107
