### ISSUE TITLE
[IntegTest] Failure RestGetRollupActionIT.test

### ISSUE THREAD

**Issue by peternied** [opensearch-project/index-management#194]
While running tests on, OpenSearch-Build @d3acfee, `./test.sh integ-test https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/994/linux/x64` found this failure:
```
REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.indexmanagement.rollup.resthandler.RestGetRollupActionIT.test getting all rollups" -Dtests.seed=4E969EC8ACDFD864 -Dtests.security.manager=false -Dtests.locale=en-AU -Dtests.timezone=Universal -Druntime.java=14


Suite: Test class org.opensearch.indexmanagement.rollup.resthandler.RestGetRollupActionIT
  2> REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.indexmanagement.rollup.resthandler.RestGetRollupActionIT.test getting all rollups" -Dtests.seed=4E969EC8ACDFD864 -Dtests.security.manager=false -Dtests.locale=en-AU -Dtests.timezone=Universal -Druntime.java=14
  2> org.opensearch.client.ResponseException: method [PUT], host [https://localhost:9200], URI [/_plugins/_rollup/jobs/qaNsSFxUIp?refresh=true], status line [HTTP/1.1 500 Internal Server Error]
    {"error":{"root_cause":[{"type":"zone_rules_exception","reason":"Unknown time-zone ID: US/Pacific-New"}],"type":"zone_rules_exception","reason":"Unknown time-zone ID: US/Pacific-New"},"status":500}
        at __randomizedtesting.SeedInfo.seed([4E969EC8ACDFD864:42F60720C6BA8DB9]:0)
        at org.opensearch.client.RestClient.convertResponse(RestClient.java:344)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:314)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:289)
        at org.opensearch.indexmanagement.TestHelpersKt.makeRequest(TestHelpers.kt:106)
        at org.opensearch.indexmanagement.TestHelpersKt.makeRequest$default(TestHelpers.kt:95)
        at org.opensearch.indexmanagement.rollup.RollupRestTestCase.createRollupJson(RollupRestTestCase.kt:93)
        at org.opensearch.indexmanagement.rollup.RollupRestTestCase.createRollup(RollupRestTestCase.kt:73)
        at org.opensearch.indexmanagement.rollup.RollupRestTestCase.createRollup$default(RollupRestTestCase.kt:71)
        at org.opensearch.indexmanagement.rollup.resthandler.RestGetRollupActionIT$test getting all rollups$rollups$1.get(RestGetRollupActionIT.kt:72)
        at org.opensearch.indexmanagement.rollup.resthandler.RestGetRollupActionIT$test getting all rollups$rollups$1.get(RestGetRollupActionIT.kt:40)
        at org.opensearch.test.OpenSearchTestCase.randomList(OpenSearchTestCase.java:917)
        at org.opensearch.indexmanagement.rollup.resthandler.RestGetRollupActionIT.test getting all rollups(RestGetRollupActionIT.kt:72)
  2> NOTE: leaving temporary files on disk at: /tmp/tmpnh4sf1wj/index-management/build/testrun/integTest/temp/org.opensearch.indexmanagement.rollup.resthandler.RestGetRollupActionIT_4E969EC8ACDFD864-001
  2> NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=883, maxMBSortInHeap=5.378528278615166, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=en-AU, timezone=Universal
  2> NOTE: Linux 5.4.147-83.259.amzn2int.x86_64 amd64/AdoptOpenJDK 14.0.2 (64-bit)/cpus=16,threads=1,free=254382752,total=536870912
  2> NOTE: All tests run in this JVM: [TransformRunnerIT, RestStartTransformActionIT, RestStopTransformActionIT, RestIndexTransformActionIT, RestExplainTransformActionIT, RestGetTransformActionIT, RestPreviewTransformActionIT, RestDeleteTransformActionIT, RestRefreshSearchAnalyzerActionIT, RefreshSearchAnalyzerActionIT, RestIndexRollupActionIT, RestExplainRollupActionIT, RestDeleteRollupActionIT, RestStopRollupActionIT, RestGetRollupActionIT]
```

This issue needs to be fixed for the 1.2.0 release.

**Comment by peternied** [comment]
Seeing this failure on build `994` @bowenlan-amzn @downsrob

**Comment by downsrob** [comment]
Doing some quick research I would bet that this is a flakey failure as it looks like US Pacific-New isn't a real timezone. Congress created a bill to add the new time zone US Pacific-New but it was never passed. Seems that some time zone lists include it and others don't, so I am guessing that it was selected from some randomized generator list where it is a valid time zone then rejected by another list where it is not. 

What is strange to me is that the log says the time zone is -Dtests.timezone=Universal, will need to look into the test setup to see where the time zone could have come from

**Comment by dbbaughe** [comment]
We use the randomZone method coming from OpenSearchTestCase @peternied

```
    public static TimeZone randomTimeZone() {
        return TimeZone.getTimeZone(randomJodaAndJavaSupportedTimezone(JAVA_TIMEZONE_IDS));
    }
```

Example test to show:

```
    fun `test this`() {
        val set = mutableSetOf<String>()
        for (i in 1..1000000) {
            set.add(randomTimeZone().id)
        }
        logger.info(set.filter { it.startsWith("US") })
        fail()
    }
```

Output: Can see US/Pacific-New in the list
```
[2021-11-12T22:27:23,597][INFO ][o.o.i.u.IndexUtilsTests  ] [test this] before test
[2021-11-12T22:27:24,719][INFO ][o.o.i.u.IndexUtilsTests  ] [test this] [US/Central, US/Mountain, US/Hawaii, US/Michigan, US/East-Indiana, US/Samoa, US/Indiana-Starke, US/Aleutian, US/Pacific-New, US/Eastern, US/Pacific, US/Alaska, US/Arizona]
[2021-11-12T22:27:24,750][INFO ][o.o.i.u.IndexUtilsTests  ] [test this] after test
```

I changed the specific test that failed to **always** use US/Pacific-New and it passes so perhaps it's something with the timezone coming from the random test util and the JDK version being used on the CI box.

I'd be curious if you add a simple test case in core (or any project in the tests) on the CI box to see if ZoneId.of("US/Pacific-New") can correctly pass.

**Comment by peternied** [comment]
Here is the callstack from the server:
```
[2021-11-12T18:33:01,887][INFO ][o.o.j.s.JobScheduler     ] [dev-dsk-petern-1e-c2bcd0c2.us-east-1.amazon.com] Scheduling job id yBqxxxEawJ for index .opendistro-ism-config .
[2021-11-12T18:33:01,902][WARN ][r.suppressed             ] [dev-dsk-petern-1e-c2bcd0c2.us-east-1.amazon.com] path: /_plugins/_rollup/jobs/qaNsSFxUIp, params: {refresh=true, rollupID=qaNsSFxUIp}
java.time.zone.ZoneRulesException: Unknown time-zone ID: US/Pacific-New
        at java.time.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:279) ~[?:?]
        at java.time.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:234) ~[?:?]
        at java.time.ZoneRegion.ofId(ZoneRegion.java:121) ~[?:?]
        at java.time.ZoneId.of(ZoneId.java:409) ~[?:?]
        at java.time.ZoneId.of(ZoneId.java:357) ~[?:?]
        at org.opensearch.indexmanagement.common.model.dimension.DateHistogram$Companion.parse(DateHistogram.kt:157) ~[?:?]
        at org.opensearch.indexmanagement.common.model.dimension.Dimension$Companion.parse(Dimension.kt:76) ~[?:?]
        at org.opensearch.indexmanagement.rollup.model.Rollup$Companion.parse(Rollup.kt:325) ~[?:?]
        at org.opensearch.indexmanagement.rollup.resthandler.RestIndexRollupAction$prepareRequest$rollup$1.invoke(RestIndexRollupAction.kt:90) ~[?:?]
        at org.opensearch.indexmanagement.rollup.resthandler.RestIndexRollupAction$prepareRequest$rollup$1.invoke(RestIndexRollupAction.kt:57) ~[?:?]
        at org.opensearch.indexmanagement.opensearchapi.OpenSearchExtensionsKt.parseWithType(OpenSearchExtensions.kt:251) ~[?:?]
        at org.opensearch.indexmanagement.rollup.resthandler.RestIndexRollupAction.prepareRequest(RestIndexRollupAction.kt:90) ~[?:?]
        at org.opensearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:105) ~[opensearch-1.2.0.jar:1.2.0]
```

Checking out the JVM version that is running with the tests

**Comment by peternied** [comment]
```
% /tmp/tmppkgdek_h/local-test-cluster/opensearch-1.2.0/jdk/bin/java --version
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)
```

**Comment by peternied** [comment]
^^^ That isn't correct, I'll make sure these are running using the correct jdk version and see if that changes anything

**Comment by dbbaughe** [comment]
@peternied Rerunning will cause the randomZone to produce a new timezone and no guarantee it'll pick US/Pacific-New again. If you want confirmation you'd have to have a unit test that validates ZoneId.of("US/Pacific-New") correctly parses.

**Comment by peternied** [comment]
I specifically reran with JDK14 and the test seed included, no failures
```
(21-11-12 23:14:14) <0> [~/git/index-management]  [main|✔]
% ./gradlew ':integTest' --tests "org.opensearch.indexmanagement.rollup.resthandler.RestGetRollupActionIT.test getting all rollups" -Dtests.seed=4E969EC8ACDFD864 -Dtests.security.manager=false -Dtests.locale=en-AU -Dtests.timezone=Universal -Druntime.java=14

> Configure project :
mixed cluster flag: false
plugin in the node: /local/home/petern/git/index-management/src/test/resources/job-scheduler/opensearch-job-scheduler-1.2.0.0-SNAPSHOT.zip
plugin in the node: /local/home/petern/git/index-management/build/distributions/opensearch-index-management-1.2.0.0-SNAPSHOT.zip
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 6.7
  OS Info               : Linux 5.4.147-83.259.amzn2int.x86_64 (amd64)
  Runtime JDK Version   : 14 (AdoptOpenJDK)
  Runtime java.home     : /local/home/petern/jdk-14.0.2+12
  Gradle JDK Version    : 14 (AdoptOpenJDK)
  Gradle java.home      : /local/home/petern/jdk-14.0.2+12
  Random Testing Seed   : 4E969EC8ACDFD864
  In FIPS 140 mode      : false
=======================================

> Task :ktlint
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jetbrains.kotlin.com.intellij.util.ReflectionUtil (file:/local/home/petern/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.4.31/6451ea797cef544e81f507b0d9959cd97ae09c0/kotlin-compiler-embeddable-1.4.31.jar) to method java.util.ResourceBundle.setParent(java.util.ResourceBundle)
WARNING: Please consider reporting this to the maintainers of org.jetbrains.kotlin.com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 3s
11 actionable tasks: 1 executed, 10 up-to-date
```
The only difference is that the cluster is a remote cluster.  I'm not sure what action we should take.  Tests should not fail intermittiately or they are very low value, but also in this case, it isn't clear that there is anything wrong with index-management that needs addressing.

**Comment by downsrob** [comment]
Support was removed for US/Pacific-New in JDK 15.0.2 https://bugs.openjdk.java.net/browse/JDK-8254679 though 15.0.1+9 was built after that, so I think that it was most likely removed in a backport as well. 

Does using the same test seed confirm that it fails with the 15.0.1+9 and not with JDK 14? If not then writing a unit test as Drew suggested and running it with each JDK version would confirm. At this point, though, it seems like flakiness was introduced because of a test environment JDK version mismatch. An action to prevent this in the future would be to make sure the jvm versions are in sync on the test environment in the future.

**Comment by peternied** [comment]
When I ran the individual test it never failed on either JVM

**Comment by downsrob** [comment]
As ISM only uses core logic for ZoneId creation and processing, and because we have only been able to replicate this when there is a JDK version mismatch between the test version and the machine JDK version, I'll close this issue on ISM and chalk it up to a test environment issue. In the future, to prevent these kinds of failures, we should include a check in core to verify that the JDK versions match, as otherwise this failure/flakiness is possible.
