### ISSUE TITLE
[BUG][DISTRIBUTION][2.0.0] IM downloading JS zip that is not exist due to no success builds

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/index-management#333]
```
+ ./gradlew assemble --no-daemon --refresh-dependencies -DskipTests=true -Dopensearch.version=2.0.0-rc1-SNAPSHOT -Dbuild.snapshot=true -Dbuild.version_qualifier=rc1
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.3.3/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
A problem occurred evaluating root project 'opensearch-index-management'.
> Can't get https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.0.0-rc1/latest/linux/x64/builds/opensearch/plugins/opensearch-job-scheduler-2.0.0.0-rc1.zip to /tmp/tmpbpozmgws/index-management/src/test/resources/job-scheduler/opensearch-job-scheduler-2.0.0.0-rc1.zip

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Build file '/tmp/tmpbpozmgws/index-management/build.gradle' line: 208

* What went wrong:
A problem occurred configuring root project 'opensearch-index-management'.
> Index 0 out of bounds for length 0

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org/

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 10s
2022-04-14 22:20:11 ERROR    Error building index-management, retry with: ./build.sh manifests/2.0.0/opensearch-2.0.0.yml --component index-management --snapshot
Traceback (most recent call last):
  File "./src/run_build.py", line 80, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 68, in main
    builder.build(build_recorder)
  File "/var/jenkins/workspace/distribution-build-opensearch/src/build_workflow/builder_from_source.py", line 55, in build
    self.git_repo.execute(build_command)
  File "/var/jenkins/workspace/distribution-build-opensearch/src/git/git_repository.py", line 83, in execute
    subprocess.check_call(command, cwd=cwd, shell=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bash /var/jenkins/workspace/distribution-build-opensearch/scripts/default/opensearch/build.sh -v 2.0.0 -q rc1 -p linux -a x64 -s true -o builds' returned non-zero exit status 1.
```

IM code is trying to get latest JS zip to build IM, but in reality there is no successful build yet in 2.0.0-alpha1, thus no latest.
This has become a catch 22 now, so IM needs latest JS but JS is not able to get from latest because the pipeline is not even complete and will fail due to IM cannot find JS.

**Comment by peterzhuamazon** [comment]
Currently will get Amit help to fix it as he is the one implement the download zip method.
