### ISSUE TITLE
[FEATURE] Make installable artifacts available for download

### ISSUE THREAD

**Issue by shdubsh** [opensearch-project/index-management#383]
**Is your feature request related to a problem?**
Plugins cannot be installed in an offline/firewalled/airgapped deployment of the minimum distribution.

**What solution would you like?**
Make available the built artifacts and dependencies for offline install on the https://opensearch.org/artifacts page or in the github releases page.

**What alternatives have you considered?**
The artifacts can be extracted manually and installed offline from the tar.gz opensearch release.

**Comment by downsrob** [comment]
Hi, I apologize, we should have updated the releases pages, but plugins should be available for download through the tags page here https://github.com/opensearch-project/index-management/tags
Does this meet your use case?

**Comment by shdubsh** [comment]
I tried your suggestion and got this result:
```
$ wget -O /tmp/1.3.3.0.zip https://github.com/opensearch-project/index-management/archive/refs/tags/1.3.3.0.zip
$ sudo /usr/share/opensearch/bin/opensearch-plugin install file:///tmp/1.3.3.0.zip 
-> Installing file:///tmp/1.3.3.0.zip
-> Downloading file:///tmp/1.3.3.0.zip
[=================================================] 100%   
-> Failed installing file:///tmp/1.3.3.0.zip
-> Rolling back file:///tmp/1.3.3.0.zip
-> Rolled back file:///tmp/1.3.3.0.zip
Exception in thread "main" java.nio.file.NoSuchFileException: /usr/share/opensearch/plugins/.installing-4082858646057834380/plugin-descriptor.properties
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:156)
	at org.opensearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:229)
	at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:811)
	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:870)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:275)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:249)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
```
I think this is because the release you linked is a source code zip file and not a built artifact.

**Comment by shdubsh** [comment]
@downsrob I think I do not have permission to reopen the issue.

**Comment by downsrob** [comment]
Sorry, about that, you are completely right.
We are working on getting plugins published to a more available place, and that is being tracked here https://github.com/opensearch-project/opensearch-build/issues/184
The current method that you can follow to do this will be to get the manifest for the version you want from maven, using a url like this https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.3/latest/linux/x64/tar/dist/opensearch/manifest.yml
From that manifest you will see the locations of the core artifacts, ex:
```
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: '1.3'
    commit_id: dae81c5f33060a986136df98dbd2f79015680f11
    location: https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.3/3878/linux/x64/tar/builds/opensearch/plugins/opensearch-index-management-1.3.3.0.zip
```
You will be able to download the plugin from the location listed there

**Comment by shdubsh** [comment]
This is great, thank you.  I'll watch that task for the published solution, but this gets me a functioning workaround until that's ready.

Closing as duplicate of opensearch-project/opensearch-build#184.
