### ISSUE TITLE
[IntegTest][Bug] index-management failed on no-security integ-test on 2.2.0

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/index-management#457]
```
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0

REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.indexmanagement.transform.TransformRunnerIT.test transform" -Dtests.seed=C62239FDE5D3B2C6 -Dtests.security.manager=false -Dtests.locale=tr-TR -Dtests.timezone=Africa/Tunis -Druntime.java=17

REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.indexmanagement.transform.TransformRunnerIT.test transform with data filter" -Dtests.seed=C62239FDE5D3B2C6 -Dtests.security.manager=false -Dtests.locale=tr-TR -Dtests.timezone=Africa/Tunis -Druntime.java=17


Suite: Test class org.opensearch.indexmanagement.transform.TransformRunnerIT
  2> REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.indexmanagement.transform.TransformRunnerIT.test transform" -Dtests.seed=C62239FDE5D3B2C6 -Dtests.security.manager=false -Dtests.locale=tr-TR -Dtests.timezone=Africa/Tunis -Druntime.java=17
  2> java.lang.AssertionError: Didn't capture search time
        at __randomizedtesting.SeedInfo.seed([C62239FDE5D3B2C6:84ACF2FF495A6BAB]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.opensearch.indexmanagement.transform.TransformRunnerIT.test transform(TransformRunnerIT.kt:69)
  2> REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.indexmanagement.transform.TransformRunnerIT.test transform with data filter" -Dtests.seed=C62239FDE5D3B2C6 -Dtests.security.manager=false -Dtests.locale=tr-TR -Dtests.timezone=Africa/Tunis -Druntime.java=17
  2> java.lang.AssertionError: Didn't capture search time
        at __randomizedtesting.SeedInfo.seed([C62239FDE5D3B2C6:E01E3914542889CA]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.opensearch.indexmanagement.transform.TransformRunnerIT.test transform with data filter(TransformRunnerIT.kt:108)
  2> NOTE: leaving temporary files on disk at: /tmp/tmphl0g9cld/index-management/build/testrun/integTest/temp/org.opensearch.indexmanagement.transform.TransformRunnerIT_C62239FDE5D3B2C6-001
  2> NOTE: test params are: codec=Lucene92, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=tr-TR, timezone=Africa/Tunis
  2> NOTE: Linux 5.4.204-124.362.amzn2int.x86_64 amd64/Eclipse Adoptium 17.0.3 (64-bit)/cpus=8,threads=1,free=126252928,total=536870912
  2> NOTE: All tests run in this JVM: [IndexManagementIndicesIT, ActionRetryIT, ActionTimeoutIT, AllocationActionIT, CloseActionIT, DeleteActionIT, ForceMergeActionIT, IndexPriorityActionIT, IndexStateManagementHistoryIT, OpenActionIT, ReadOnlyActionIT, ReadWriteActionIT, ReplicaCountActionIT, RolloverActionIT, RollupActionIT, ShrinkActionIT, SnapshotActionIT, TransitionActionIT, ManagedIndexCoordinatorIT, MigrationServicesIT, ISMTemplateRestAPIIT, IndexStateManagementRestApiIT, RestAddPolicyActionIT, RestChangePolicyActionIT, RestExplainActionIT, RestRemovePolicyActionIT, RestRetryFailedManagedIndexActionIT, ManagedIndexRunnerIT, RefreshSearchAnalyzerActionIT, RestRefreshSearchAnalyzerActionIT, FieldCapsFilterIT, RollupInterceptorIT, RestDeleteRollupActionIT, RestExplainRollupActionIT, RestGetRollupActionIT, RestIndexRollupActionIT, RestStartRollupActionIT, RestStopRollupActionIT, RollupRunnerIT, SMRunnerIT, RestDeleteSnapshotManagementIT, RestExplainSnapshotManagementIT, RestGetSnapshotManagementIT, RestIndexSnapshotManagementIT, RestStartSnapshotManagementIT, RestStopSnapshotManagementIT, TransformRunnerIT]

289 tests completed, 2 failed, 6 skipped

=== Standard output of node `node{::integTest-0}` ===

=== Standard error of node `node{::integTest-0}` ===

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integTest'.
> There were failing tests. See the report at: file:///tmp/tmphl0g9cld/index-management/build/reports/tests/integTest/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25m 2s
~
```

**Comment by praveensameneni** [comment]
The issue happens when the search time is lower than 1. Removing 2.2 label for now and keeping the issue open to fix for next release.

**Comment by khushbr** [comment]
This is a flaky test which has been intermittently failing. Here is another occurrence https://github.com/opensearch-project/index-management/runs/7569001547?check_suite_focus=true#step:5:207

The assert is for `metadata.stats` to have non-zero index and search time, refer https://github.com/opensearch-project/index-management/blame/a7fb77eb2761f0846f720340ac83ee6420a330b2/src/test/kotlin/org/opensearch/indexmanagement/transform/TransformRunnerIT.kt#L107
