### ISSUE TITLE
[BUG] data_nanos with decimal points in rollup jobs fails with NumberFormatException

### ISSUE THREAD

**Issue by rishabhmaurya** [opensearch-project/index-management#767]
**What is the bug?**
`data_nanos` field type can have numbers with decimal points. The following codepath doesn't take care of such cases and will result in error -
https://github.com/opensearch-project/index-management/blob/main/src/main/kotlin/org/opensearch/indexmanagement/rollup/RollupMetadataService.kt#LL197C1-L197C1
```kotlin
val firstHitTimestamp = response.hits.hits.first().field(dateHistogram.sourceField).getValue<String>()?.toLong()?: return StartingTimeResult.NoDocumentsFound
```
**Exception -** 
```
Failed to initialize rollup metadata
java.lang.NumberFormatException: For input string: "1682243656233.660467"
    at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.base/java.lang.Long.parseLong(Long.java:692)
    at java.base/java.lang.Long.parseLong(Long.java:817)
    at org.opensearch.indexmanagement.rollup.RollupMetadataService.getInitialStartTime(RollupMetadataService.kt:197)
    at org.opensearch.indexmanagement.rollup.RollupMetadataService.access$getInitialStartTime(RollupMetadataService.kt:48)
    at org.opensearch.indexmanagement.rollup.RollupMetadataService$getInitialStartTime$1.invokeSuspend(RollupMetadataService.kt)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```

**How can one reproduce the bug?**
1. Set up rollup job with source index having date histogram of field type `date_nanos`
2. Add a document in source index with histogram field value in decimal. 
3. Run the rollup job.

**Comment by rishabhmaurya** [comment]
For any aggregations, we lose the nanoseconds precision so is the case here with date histograms. I don't see any issue in converting it to millis.

**Comment by petardz** [comment]
> For any aggregations, we lose the nanoseconds precision so is the case here with date histograms. I don't see any issue in converting it to millis.

I got confused for a moment.. That decimal part is definitely nanos..

Pushed a quick PR for this
